* Authors
  - Tim Gillis
  - Tom Sydney Kerckhove

* Configuration
  - Config.h
    - DEBUG (boolean)
      Set this to on to debug the system.
  - MotorConfig.h
    - LEFT_ENABLE (int)
      The enable pin for the left motor
    - LEFT_PHASE (int)
      The phase pin for the left motor
    - RIGHT_ENABLE (int)
      The enable pin for the right motor
    - RIGHT_PHASE (int)
      The phase pin for the right motor
    - MODE (int)
      The mode pin for the motor controller
  - SensorConfig.h
    - SHORT_LEFT (int)
      The input pin for the left short-range motor.
    - SHORT_RIGHT (int)
      The input pin for the right short-range motor.
    - LONG (int)
      The input pin for the long-range motor.
* Installation
** Motors
For both motors the following needs to be done
Motor A is Right, motor B is left.
    - Connect the motor wires to the O1 and O2 on the motor controller.
** Motor controller
   - Connect the mode pin of the controller to a 5V pin on the arduino 
   - For both motors
     - Connect the phase pin of the controller with a "~" pin on the arduino
     - Connect the enable pin of the controller with a digital pin on the arduino
** Sensors
   - Short range
     - Connect the Power pin to the 5V pin on the arduino
     - Connect the ground pin to the ground pin on the arduino
     - Connect the output pin to a digital pin on the arduino
   - Long range
     - Connect the output pin to an analog pin on the arduino
** Battery Pack
   - Connect the 9V wire of the of the battery pack to the V_n pin on the arduino.
   - Connect the ground wire of the battery packt to the ground pin on the arduino.
** Countdown Led
   We need to have a countdown led according to the rules.
   We can either use the led on pin 13  for this, or install one of our own.
   I prefer the latter but we need to check whether we can fit that on the circuit bord.

* File manifest
  - ai
  - Config.h
  - Motor.cpp
  - Motor.h
  - MotorConfig.h
  - Sensor.cpp
  - Sensor.h
  - SensorConfig.h
  - Test.cpp
  - Test.h

* Known Issues
  Nothing works yet.
